name: honey_admin
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+11

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.3.2
  get: ^4.6.5
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  persistent_bottom_nav_bar: ^6.2.1
  infinite_scroll_pagination: ^4.0.0
  cached_network_image: ^3.3.1
  built_value: ^8.4.4
  built_collection: ^5.1.1
  intl: ^0.19.0
  win32 : ^5.11.0
  #get_storage: ^2.1.1
  flutter_launcher_icons: ^0.14.3

  flutter_easyloading: ^3.0.5
  jwt_decoder: ^2.0.1
  google_fonts: ^6.2.1
  loading_animation_widget: ^1.2.0+4
  change_app_package_name: ^1.1.0
  flutter_dotenv: ^5.2.1
  hive: ^2.2.3 #using hive instead of get storage package because get storage have a problem in refresh token.
  hive_flutter: ^1.1.0
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  built_value_generator: ^8.4.4
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FF7941D"
  remove_alpha_ios: true


flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/lottie/
    - assets/icons/
    - assets/.env

  fonts:
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexSansArabic-Medium.ttf
          weight: 500
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
          weight: 700
